# Generated by Django 5.1.5 on 2025-02-18 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='permisos',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('APROBADO', 'aprobado'), ('RECHAZADO', 'rechazado')], default='PENDIENTE', max_length=10)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleadoprofile')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empresaprofile')),
            ],
        ),
    ]
