# Generated by Django 5.1.5 on 2025-02-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_empresaprofile_permisos_gasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaprofile',
            name='codigo_postal',
        ),
        migrations.RemoveField(
            model_name='empresaprofile',
            name='pais',
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
