# Generated by Django 5.1.5 on 2025-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_empresaprofile_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadoprofile',
            name='dni',
            field=models.CharField(default='PENDIENTE', max_length=20, unique=True),
        ),
    ]
