# Generated by Django 5.1.5 on 2025-02-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_gasto_estado_viaje_gasto_viaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='coste',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
