# Generated by Django 5.1.5 on 2025-03-05 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 10, 40, 34, 30415, tzinfo=datetime.timezone.utc)),
        ),
    ]
