# Generated by Django 5.1.5 on 2025-03-05 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_must_change_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 5, 12, 7, 41, 386741, tzinfo=datetime.timezone.utc)),
        ),
    ]
