# Generated by Django 5.1.5 on 2025-03-10 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='coste',
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 10, 10, 37, 17, 375017, tzinfo=datetime.timezone.utc)),
        ),
    ]
