# Generated by Django 5.1.5 on 2025-03-17 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_passwordresettoken_expires_at_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 12, 25, 4, 420847, tzinfo=datetime.timezone.utc)),
        ),
    ]
