# Generated by Django 5.1.5 on 2025-03-24 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_viaje_empresa_visitada_viaje_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='dias_viajados',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 11, 43, 16, 421936, tzinfo=datetime.timezone.utc)),
        ),
    ]
