# Generated by Django 5.1.5 on 2025-03-27 09:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_viaje_dias_viajados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 10, 53, 30, 75274, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleadoprofile')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='users.viaje')),
            ],
        ),
    ]
