# Generated by Django 5.1.5 on 2025-04-02 08:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_passwordresettoken_expires_at_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('JUSTIFICAR', 'Justificante solicitado')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 9, 9, 51, 802420, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MensajeJustificante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_justificante', to='users.gasto')),
            ],
        ),
    ]
