# Generated by Django 5.1.5 on 2025-04-02 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_gasto_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajejustificante',
            name='archivo_justificante',
            field=models.FileField(blank=True, null=True, upload_to='respuestas_justificantes/'),
        ),
        migrations.AddField(
            model_name='mensajejustificante',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='mensajejustificante',
            name='respuesta',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 9, 35, 24, 14712, tzinfo=datetime.timezone.utc)),
        ),
    ]
