# Generated by Django 5.1.5 on 2025-04-02 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_mensajejustificante_archivo_justificante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 10, 23, 21, 596805, tzinfo=datetime.timezone.utc)),
        ),
    ]
