# Generated by Django 5.1.5 on 2025-04-02 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 10, 34, 2, 126434, tzinfo=datetime.timezone.utc)),
        ),
    ]
