# Generated by Django 5.1.5 on 2025-04-02 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 2, 11, 17, 43, 474671, tzinfo=datetime.timezone.utc)),
        ),
    ]
