# Generated by Django 5.1.5 on 2025-04-04 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 8, 29, 53, 325577, tzinfo=datetime.timezone.utc)),
        ),
    ]
