# Generated by Django 5.1.5 on 2025-04-22 09:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_passwordresettoken_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 10, 16, 37, 543843, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En curso'), ('EN_REVISION', 'En revision'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
        migrations.CreateModel(
            name='DiaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('exento', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='users.viaje')),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='users.diaviaje'),
        ),
    ]
