# Generated by Django 5.1.5 on 2025-04-22 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='fecha_gasto',
            field=models.DateField(blank=True, help_text='Fecha del gasto', null=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 11, 26, 40, 726845, tzinfo=datetime.timezone.utc)),
        ),
    ]
