# Generated by Django 5.1.5 on 2025-10-08 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_mensajejustificante_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaviaje',
            name='exento',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 10, 12, 29, 739713, tzinfo=datetime.timezone.utc)),
        ),
    ]
