# Generated by Django 5.1.5 on 2025-10-08 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_diaviaje_exento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoprofile',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 10, 35, 46, 494806, tzinfo=datetime.timezone.utc)),
        ),
    ]
