# Generated by Django 5.1.5 on 2025-10-08 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_empleadoprofile_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadoprofile',
            name='dni',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 10, 40, 10, 13993, tzinfo=datetime.timezone.utc)),
        ),
    ]
