# Generated by Codex on 2025-02-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_empleadoprofile_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaprofile',
            name='force_release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='has_pending_review_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='last_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='manual_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='next_release_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresaprofile',
            name='periodicity',
            field=models.CharField(choices=[('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], default='TRIMESTRAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ViajeReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_REVISION', 'En revision'), ('REABIERTO', 'Reabierto'), ('REVISADO', 'Revisado')], max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('pais', models.CharField(blank=True, max_length=255, null=True)),
                ('es_internacional', models.BooleanField(default=False)),
                ('destino', models.CharField(max_length=255)),
                ('dias_viajados', models.PositiveIntegerField(default=1)),
                ('empresa_visitada', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo', models.TextField(blank=True, max_length=500, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_snapshots', to='users.empleadoprofile')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viaje_snapshots', to='users.empresaprofile')),
                ('viaje', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_snapshot', to='users.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='GastoReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('JUSTIFICAR', 'Justificante solicitado')], max_length=10)),
                ('fecha_gasto', models.DateField(blank=True, help_text='Fecha del gasto', null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_snapshots', to='users.empleadoprofile')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasto_snapshots', to='users.empresaprofile')),
                ('gasto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_snapshot', to='users.gasto')),
                ('viaje_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_snapshot', to='users.viajereviewsnapshot')),
            ],
        ),
        migrations.CreateModel(
            name='DiaViajeReviewSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('exento', models.BooleanField(default=True)),
                ('revisado', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('dia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_snapshot', to='users.diaviaje')),
                ('viaje_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_snapshot', to='users.viajereviewsnapshot')),
            ],
        ),
    ]
