# Generated by Django 5.1.5 on 2025-11-03 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_empresaprofile_periodicity_and_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 11, 13, 36, 542246, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='estado',
            field=models.CharField(choices=[('EN_REVISION', 'En revision'), ('REABIERTO', 'Reabierto'), ('REVISADO', 'Revisado')], default='EN_REVISION', max_length=15),
        ),
    ]
