# Generated by Django 5.1.5 on 2025-11-03 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('VIAJE_SOLICITADO', 'Viaje solicitado'), ('VIAJE_APROBADO', 'Viaje aprobado'), ('GASTO_REGISTRADO', 'Gasto registrado'), ('REVISION_FECHA_LIMITE', 'Fecha límite de revisión')], max_length=50),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 11, 36, 47, 83248, tzinfo=datetime.timezone.utc)),
        ),
    ]
