# Generated by Django 5.1.5 on 2025-11-07 10:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_notificacion_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 11, 25, 41, 670653, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='ConversacionLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='users.conversacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_conversacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lectura de conversación',
                'verbose_name_plural': 'Lecturas de conversación',
                'unique_together': {('conversacion', 'usuario')},
            },
        ),
    ]
