# Generated by Django 5.1.5 on 2025-11-07 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 11, 29, 22, 483151, tzinfo=datetime.timezone.utc)),
        ),
    ]
