# Generated by Django 5.1.5 on 2025-11-07 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_drop_authtoken_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 14, 29, 33, 810069, tzinfo=datetime.timezone.utc)),
        ),
    ]
